version: "3"

services:
  app_blue:
    build: ./app_blue
    ports:
      - "3000:3000"

  app_green:
    build: ./app_green
    ports:
      - "3001:3000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app_blue
      - app_green
